### ISSUE TITLE
Clipping length error

### ISSUE THREAD

**Issue by Dorian-Chapoulie** [muxinc/mux-node-sdk#118]
Hello,

When I try to clip an asset, i get this error: 
**Effective clip duration of _$TIME_ too short, minimum clip duration is 5.000 seconds**

but my input is 
`[{
  url: ...,
  start_time: 0.4,
  end_time: 5.43,
}];`
so the length is 5.03

and the error is: 
**[invalid_parameters]:**
**Effective clip duration of 4.730 too short, minimum clip duration is 5.000 seconds**

After some tests, it looks like there is an offset of 0.3s:

Start: 0.37
End: 5.43
length = 5.06
=> error: 4.760 (5.06 - 4.76 = 0.3)

Start: 0.33
End: 5.43
length = 5.1
=> error: 4.800 (5.1 - 4.8 = 0.3)

Start: 0.3
End: 5.43
length = 5.13
=> error: 4.830 (5.13 - 4.83 = 0.3)

Start: 0.27
End: 5.43
length = 5.16
=> error: 4.860 (5.16 - 4.86 = 0.3)

**Comment by dylanjha** [comment]
Hi @Dorian-Chapoulie, thanks for opening this.

This is a little surprising and it might depend on the length of the underlying source. Can you use the intercom chat bubble in the bottom right corner of the Mux dashboard to open a support ticket with our team?

We'll need the asset ID for this one you're testing with and I'd be happy to take a closer look!

**Comment by aminamos** [comment]
Closing, alternate thread opened
