### ISSUE TITLE
Does not work with Vite/Sveltekit 

### ISSUE THREAD

**Issue by benwoodward** [muxinc/mux-node-sdk#120]
Error only occurs when running `npm run build`:

```
> Using @sveltejs/adapter-netlify
> Named export 'Webhooks' not found. The requested module '@mux/mux-node' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@mux/mux-node';
const { Webhooks } = pkg;

file:///Users/ben/dev/mux-node-esm-issue/.svelte-kit/output/server/app.js:4
import { Webhooks } from "@mux/mux-node";
         ^^^^^^^^
SyntaxError: Named export 'Webhooks' not found. The requested module '@mux/mux-node' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@mux/mux-node';
const { Webhooks } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:142:20)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async prerender (file:///Users/ben/dev/mux-node-esm-issue/node_modules/@sveltejs/kit/dist/chunks/index6.js:80:14)
    at async Object.prerender (file:///Users/ben/dev/mux-node-esm-issue/node_modules/@sveltejs/kit/dist/chunks/index6.js:312:5)
    at async adapt (file:///Users/ben/dev/mux-node-esm-issue/node_modules/@sveltejs/adapter-netlify/index.js:34:4)
    at async adapt (file:///Users/ben/dev/mux-node-esm-issue/node_modules/@sveltejs/kit/dist/chunks/index6.js:338:2)
    at async file:///Users/ben/dev/mux-node-esm-issue/node_modules/@sveltejs/kit/dist/cli.js:887:5
```

`adapter-netlify` / SvelteKit are not recognising `@mux/mux-node` as an ESM package. This could be due to `"type": "module"` not being present in the `package.json`. Could also be that `"main": "src/index.js"` needs to be replaced with `"exports": "src/index.js"`

EDIT: Repro repo: https://github.com/benwoodward/mux-node-esm-issue (Run `npm run build` to see the error`)

**Comment by dylanjha** [comment]
Hi @benwoodward, thanks for reaching out, and thanks for providing a repo with the steps to reproduce. That is always appreciated! 🙏🏼 

The top-level export is the `Mux` constructor and that needs to be called with `new`, in your example you would need to call `new` on the `pkg` variable, like this:

```
import pkg from '@mux/mux-node';
 const { Webhooks } = new pkg()
```

It's a little more intuitive to name the import `Mux` so it looks like a constructor:

```js
import Mux from '@mux/mux-node';
const { Webhooks } = new Mux();
```

This isn't so much of a module export issue, it's the design of the SDK.

The reason for this is that the subclasses in the `Mux` namespace (`Video`, `Data`, `Webhooks`, etc.) all have access to the api token and api secret. The api key and secret can be provided in two ways:

1. passed into the constructor `new Mux(apiToken, apiSecret)`
2. The SDK will check for `process.env.MUX_TOKEN_ID` and `process.env.MUX_TOKEN_SECRET`

Does that make sense? I tried this out the fork and was able to run the build when I provided those `process.env` variables.

## Diff:

```diff
diff --git a/src/routes/endpoints/muxWebhook.js b/src/routes/endpoints/muxWebhook.js
index 01c6abf..dbb6cc1 100644
--- a/src/routes/endpoints/muxWebhook.js
+++ b/src/routes/endpoints/muxWebhook.js
@@ -1,4 +1,6 @@
-import { Webhooks } from '@mux/mux-node';
+import Mux from '@mux/mux-node';
+
+const { Webhooks } = new Mux();

 // const webhookSecret = import.meta.env.VITE_MUX_WEBHOOK_SECRET;
 const webhookSecret = 'abc123';
```

## Build

```shell
❯ MUX_TOKEN_ID=xxxxx MUX_TOKEN_SECRET=yyyyy npm run build

> ~TODO~@0.0.1 build
> svelte-kit build

vite v2.4.1 building for production...
✓ 14 modules transformed.
.svelte-kit/output/client/_app/manifest.json                    1.21kb
.svelte-kit/output/client/_app/layout.svelte-134713a4.js        0.50kb / brotli: 0.29kb
.svelte-kit/output/client/_app/pages/index.svelte-5931bbc5.js   0.79kb / brotli: 0.41kb
.svelte-kit/output/client/_app/assets/start-a8cd1609.css        0.16kb / brotli: 0.10kb
.svelte-kit/output/client/_app/error.svelte-ea48e0c7.js         1.55kb / brotli: 0.64kb
.svelte-kit/output/client/_app/chunks/vendor-2b0cfca2.js        6.42kb / brotli: 2.46kb
.svelte-kit/output/client/_app/start-2694ddb9.js                17.27kb / brotli: 5.52kb
vite v2.4.1 building SSR bundle for production...
✓ 10 modules transformed.
.svelte-kit/output/server/app.js   10.28kb

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-netlify
  ✔ done

```

**Comment by benwoodward** [comment]
Ohhhh I see. Okay great. Thanks for such a quick response. 

Strange that my code works in dev mode. Maybe this is just something to do with how Vite works that I don't understand.

**Comment by dylanjha** [comment]
@benwoodward thanks for the follow up

With regards to Vite in dev mote, I suspect that Vite optimistically loads the app, so the file in `src/routes/endpoints/muxWebhook.js` doesn't imported or compiled until it is actually called (in this case, your application receives an external webhook and now has to process it)

**Comment by benwoodward** [comment]
My Webhook endpoints were working fine when testing with `ngrok`. Perhaps Vite does some clever transpilation stuff somehow.

**Comment by dylanjha** [comment]
hmmm, interesting -- okay not sure about that one with Vite, but either way, thanks for the follow up!

**Comment by benwoodward** [comment]
Wait, I think I just write really terrible code 😂 

```javascript
  const isValidSignature = Webhooks.verifyHeader(
    JSON.stringify(request.body),
    signature,
    webhookSecret
  );

    if (!isValidSignature) { throw new Error('Invalid signature') };
```

**Comment by dylanjha** [comment]
@benwoodward a couple notes about your code.

1. See [`verifyHeader`](https://github.com/muxinc/mux-node-sdk#verifying-webhook-signatures) in the README -- it will actually raise an exception if the signature is invalid

```
/*
  If the header is valid, this will return `true`
  If invalid, this will throw one of the following errors:
    * new Error('Unable to extract timestamp and signatures from header')
    * new Error('No signatures found with expected scheme');
    * new Error('No signatures found matching the expected signature for payload.')
    * new Error('Timestamp outside the tolerance zone')
*/

/*
  `rawBody` is the raw request body. It should be a string representation of a JSON object.
  `header` is the value in request.headers['mux-signature']
  `secret` is the signing secret for this configured webhook. You can find that in your webhooks dashboard
           (note that this secret is different than your API Secret Key)
*/

Mux.Webhooks.verifyHeader(rawBody, header, secret);
```

I noticed that there was a comment in there incorrectly saying: `// returns a `boolean` with value `true` if the signature is valid`. Just put up a PR to fix that: https://github.com/muxinc/mux-node-sdk/pull/121

2. Instead of doing `JSON.stringify(request.body)` I would recommend getting access to the raw request body. Stringifying JSON isn't deterministic in different languages. The signature in `mux-signature` is created according to the raw request body that is sent over the wire, so in order to verify the signature in a reliable way, you will want to use the raw body instead of the body that has gone through `JSON.parse` and then `JSON.stringify`.

Even though that method may work in when you're manually testing, it's sub-optimal and could fail in the future or on certain edge cases.

We have a note about this:

> Note that when passing in the payload (rawBody) you want to pass in the raw un-parsed request body, not the parsed JSON. 

I'd have to take a look at Vite to see how to get the rawBody, is that easy?

**Comment by benwoodward** [comment]
Actually found that the `const { Webhooks } = new Mux();` throws an error: 

Throws `Cannot read property 'verifyHeader' of undefined`
```javascript
import Mux from '@mux/mux-node';

const { Webhooks } = new Mux();

// snip

  isValidSignature = Webhooks.verifyHeader(
    JSON.stringify(request.body),
    signature,
    webhookSecret
  );
```

Works:
```javascript
import Mux from '@mux/mux-node';

const { Webhooks } = Mux;

// snip

  isValidSignature = Webhooks.verifyHeader(
    JSON.stringify(request.body),
    signature,
    webhookSecret
  );
```

Second example ↑ is what's in the README. 

> See verifyHeader in the README -- it will actually raise an exception if the signature is invalid. So you'll want to wrap it in a try / catch block

Aha, ok thanks 🙂 

> Instead of doing JSON.stringify(request.body) I would recommend getting access to the raw request body. Stringifying JSON isn't deterministic in different languages. The signature in mux-signature is created according to the raw request body that is sent over the wire, so in order to verify the signature in a reliable way, you will want to use the raw body instead of the body that has gone through JSON.parse and then JSON.stringify.

Oh, thanks for pointing this out, this code was written with a lot of haste. [`rawBody` is accessible in Sveltekit requests](https://kit.svelte.dev/docs#routing-endpoints) yes.

Here's the updated code for my Mux webhook in Sveltekit + Dgraph (in case anyone's googling this!)

```javascript
import { dgraphClient } from '$lib/configs/dgraph-client.ts';
import Mux from '@mux/mux-node';

const { Webhooks } = Mux;

const webhookSecret = import.meta.env.VITE_MUX_WEBHOOK_SECRET;

export async function post(request) {
  const signature = request.headers['mux-signature'];
  const txn = dgraphClient.newTxn();

  let isValidSignature = false;

  try {
    isValidSignature = Webhooks.verifyHeader(
      request.rawBody,
      signature,
      webhookSecret
    );
  } catch(e) {
    console.log(e);
  }

  try {
    if (isValidSignature === false) { throw new Error('Invalid signature') };

    if (request.body.type === 'video.asset.ready') {
      const playbackId = request.body.data.playback_ids[0].id;
      const uploadId = request.body.data.upload_id;
      const mutationJson = await upsertVideoJson(uploadId, playbackId);
      const videoRecord = await txn.mutate({ mutation: JSON.stringify(mutationJson) });
      const videoRecordId = videoRecord.data.uids.videoRecord;

      await txn.commit();
    };
  } catch(e) {
    if (e === dgraph.ERR_ABORTED) {
      console.log(e)
    } else {
      throw e;
    }
  } finally {
    await txn.discard();

    return {
      body: {
        received: true
      }
    }
  }
}


async function upsertVideoJson(uploadId, playbackId) {
  return {
    query: `{
      var(func: type(Video)) @filter(eq(Video.muxUploadId, \"${uploadId}\")) {
        v as uid
      }
    }`,
    set: [
      {
        "uid": "uid(v)",
        "Video.muxStatus": 'video.asset.ready',
        "Video.muxPlaybackId": playbackId
      }
    ]
  };
}
```

**Comment by dylanjha** [comment]
@benwoodward ah yeah, you're totally right 😄 

`Webhooks` is a static attribute on the `Mux` constructor whereas `Video` and `Data` are on the instance. Thanks for clarifying and posting the code sample!

```
import Mux from '@mux/mux-node';

const { Webhooks } = Mux
const { Video, Data } = new Mux(accessToken, secret);
```
