### ISSUE TITLE
TypeError: The superclass is not a constructor.

### ISSUE THREAD

**Issue by AbdallaMohammed** [muxinc/mux-node-sdk#122]
Code:

```js
import Mux from '@mux/mux-node'

const { Video } = new Mux(token, secret)
```

Environment: VueJS (3.1.4), Vite (2.4.1)

Problem: The previous code always gives this error "TypeError: The superclass is not a constructor."

**Comment by aminamos** [comment]
@AbdallaMohammed are you still experiencing this issue? If so, did you install mux-node-sdk with npm or yarn?

**Comment by AbdallaMohammed** [comment]
@aminamos I installed max-node-sdk with rpm and yes I'm still facing this problem.

**Comment by dylanjha** [comment]
@AbdallaMohammed if you're able to create a repo with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), we'd be happy to debug it and see what's going on

**Comment by philcluff** [comment]
Hey @AbdallaMohammed, please reopen this if you're still seeing this problem and we'll take a look.

Thanks.
