### ISSUE TITLE
Incorrect types for MetricsBreakdownQueryParams et al

### ISSUE THREAD

**Issue by cwqt** [muxinc/mux-node-sdk#123]
MUX Data API reference says that possible values are "95th" "median" "avg" "count" "sum" <https://docs.mux.com/api-reference/data#operation/list-breakdown-values>
![Skjermbilde 2021-07-21 kl  2 34 33 pm](https://user-images.githubusercontent.com/61694629/126497624-9a668bd4-14f1-4ae8-a672-8a72a320ce2d.png)

Yet the types in `MetricsBreakdownQueryParams` are only `'95th' | 'median' | 'avg'`

![Skjermbilde 2021-07-21 kl  2 34 55 pm](https://user-images.githubusercontent.com/61694629/126497629-06d413ce-082c-4e7f-ab72-b1f723f342b2.png)

Same applies for `MetricsOverallQueryParams` & `MetricsTimeseriesQueryParams`

**Comment by philcluff** [comment]
Thanks for reporting @cwqt  , we'll take a look.

**Comment by dylanjha** [comment]
Hi @cwqt thanks for reporting. We have a version 8 in beta with much better TypeScript support you may be interested in trying out. See here for details:

https://github.com/muxinc/mux-node-sdk/issues/327
