### ISSUE TITLE
Maximum number of filters for the requested metric is 0

### ISSUE THREAD

**Issue by cwqt** [muxinc/mux-node-sdk#126]
Trying to use filters when on the 'Starter' MUX data tier returns the following error: 

> maximum number of filters for the requested metric is 0

```ts
        const data = await mux.connection.Data.Metrics.breakdown('views', {
          group_by: 'video_id',
          timeframe: [start.toString(), end.toString()],
          measurement: 'count',
          filters: [`video_id:${primary._id}`]
        });
```

Is this because of the pricing tier not having filters? I know this isn't the repo to raise since it's an issue with the internal API, but having something that at-least hints to the fact that a higher tier is required for filtering would be useful.

![image](https://user-images.githubusercontent.com/61694629/126514156-c172e34f-70c2-4516-b5cb-460bebc35808.png)

**Comment by dylanjha** [comment]
Hi @cwqt  yes, that's correct. The starter plan for Mux Data doesn't offer filtering capabilities. Thanks for opening in case other folks find this and I'll see if we can make the error message more clear on the API side.
