### ISSUE TITLE
Security: Update axios to 0.25.0

### ISSUE THREAD

**Issue by TonyPapousekLC** [muxinc/mux-node-sdk#137]
There's a security bug in `follow-redirects`. Axios addresses this in <https://github.com/axios/axios/pull/4379> and release https://github.com/axios/axios/releases/tag/v0.25.0

Please update this package to use the fixed version.

**Comment by eropple** [comment]
Part of #138

**Comment by eropple** [comment]
`3.3.2` released with the Axios update; `4.0.0` released with more general spring-cleaning updates.

Thanks for pinging us on this! Much appreciated.

**Comment by TonyPapousekLC** [comment]
Thanks! I love the fast-as-lightning response
