### ISSUE TITLE
Mux JWT helper does not support playback_restriction_id

### ISSUE THREAD

**Issue by paul-uz** [muxinc/mux-node-sdk#140]
According to step 4, https://docs.mux.com/guides/video/secure-video-playback#4-generate-a-json-web-token, the `playback_restriction_id` can be added to the JWT claims, yet the Mux JWT helper does not accept a `playback_restriction_id` anywhere.

How can I add `playback_restriction_id` to the JWT signing process?

**Comment by paul-uz** [comment]
Hi @philcluff that seems to work.

I first tried added it to the baseOptions, but that didn't work. Adding it to params did the trick.

Could you please look at updating the documentation with this information?

**Comment by philcluff** [comment]
Glad it worked for you, I've asked the team here to either update the docs and/or add this to the helper explicitly.

Thanks!
