### ISSUE TITLE
Deprecated api field: low_latency instead of latency_mode

### ISSUE THREAD

**Issue by digiz3d** [muxinc/mux-node-sdk#151]
Hello!

Small issue using `5.0.0-rc.5`
According to the api documentation, this package types currently exposes outdated fields for livestreams creation.

We currently have to use these params in `mux.LiveStreams.create` method
```ts
low_latency: true,
playback_policy: 'public',
new_asset_settings: {
  playback_policy: 'public',
},
```
while it should probably be 
```ts
latency_mode: 'low',
playback_policy: 'public',
new_asset_settings: {
  playback_policy: 'public',
},
```

I don't have much time right now to make a PR, so feel free to fix it before I do ;D

Have a great day

**Comment by eropple** [comment]
Hey, thanks for dropping this issue in. We'll get this handled.
