### ISSUE TITLE
Missing `status` parameter for list live streams API 

### ISSUE THREAD

**Issue by LauraBeatris** [muxinc/mux-node-sdk#158]
### Summary

The `list` method from `LiveStream` has a `ListParams` interface, which doesn't include certain params mentioned in the Mux API docs

SDK interface:
https://github.com/muxinc/mux-node-sdk/blob/f70956dcb418f0f6e4c56bd0c2aabaf5625521fa/src/video/domain.ts#L250-L255

From docs:
![Screenshot 2022-05-03 at 10 45 16](https://user-images.githubusercontent.com/48022589/166419436-e914f859-b734-4842-ae87-c74906644f0f.png)

### Use case 

TS compiler gives an error for use cases where live streams need to be filtered by `status`, since the parameters interface doesn't contain this key 

The workaround that I'm doing at the moment is by asserting the whole object to `ListParams`, but it's not type-safe, or at least I could define a union for `status` and compose another interface on top of that but wouldn't be tied to the SDK 

```
VideoAPI.LiveStreams.list({ status } as ListParams)
```

### Expected behavior

Introduce `status` union type as a parameter for Live Stream filtering

**Comment by eropple** [comment]
Hi there - apologies for the delay in getting back to this. Looks like we missed this. For background, all of our SDKs except Node and Elixir are autogenerated; this fell through the cracks, and we're working internally to make that better.

You can expect a fix by EOD Monday, US time.

**Comment by eropple** [comment]
Merged and released as **v5.0.2**. Thanks, and apologies again for the delay.

**Comment by LauraBeatris** [comment]
@eropple Thank you!
