### ISSUE TITLE
Retrieve an Asset. [Video.Assets.get() Issue]

### ISSUE THREAD

**Issue by EhanDuan** [muxinc/mux-node-sdk#166]
Hi,

I tried to retrieve an asset by asset_id.  And I wanted to get several properties of that asset, like `asset.playback_ids[0].id`.

I was expecting no errors on `asset.playback_ids[0].id`. But it popped up like this.
<img width="834" alt="image" src="https://user-images.githubusercontent.com/75397936/171278881-382ba49a-b6bb-4c21-8cd4-26734ce68d71.png">

So I try to print what happened in `asset`. When I print the `asset` in the console, I got that the `asset` is an object of `Promise`.   I checked the source code for get method. It says it returns a resolved promise. Does it mean I am supposed to get a fulfilled promise, which means I can directly use `asset.playback_ids[0].id` ?

How do I handle this error? The codes are shown below.
```ts
  const [isUploading, setIsUploading] = useState(false);
  const [isPreparing, setIsPreparing] = useState(false);
  const [uploadId, setUploadId] = useState(null);
  const [progress, setProgress] = useState(null);
  const [errorMessage, setErrorMessage] = useState("");
  const inputRef = useRef(null);

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [tags, setTags] = useState("");

  const { data, error } = useSwr(
    () => (isPreparing ? `/api/upload/${uploadId}` : null),
    fetcher,
    { refreshInterval: 5000 }
  );

  const getAsset = async () => {
    const asset = await Video.Assets.get(upload.asset_id);
    return asset;
  };

  const upload = data && data.upload;
  useEffect(() => {
    if (upload && upload.asset_id) {
      const colRef = collection(db, "Videos");
      // query from mux about duration, thumb_url, vid_url
      // asset's type is promise
      const asset = getAsset();

      asset.then(() => {
        console.log("asset: " + asset);
        addDoc(colRef, {
          description: description,
          tags: tags.split(","),
          title: title,
          duration: asset.duration,
          thumb_url: `https://image.mux.com/{asset.playback_ids[0].id}/thumbnail.{png|jpg}`,
          vid_asset_id: upload.asset_id,
          vid_playback_id: asset.playback_ids[0].id,
          vid_url: `https://stream.mux.com/{asset.playback_ids[0].id}.m3u8`, // playback url  : "https://stream.mux.com/{PLAYBACK_ID}.m3u8"
          vid_tier: "free",
          created_at: serverTimestamp()
        });
      });
    }
  }, [upload]);
```

**Comment by EhanDuan** [comment]
It is my lack of promise knowledge causing that. Here is the correct one
```ts
 useEffect(() => {
    if (upload && upload.asset_id) {
      const colRef = collection(db, "Videos");
      // query from mux about duration, thumb_url, vid_url
      // asset's type is promise
      const assetPromise = getAsset();
      console.log(assetPromise);

      assetPromise.then((asset) => {
        console.log("In the then function");
        console.log(asset);
        addDoc(colRef, {
          description: description,
          tags: tags.split(","),
          title: title,
          duration: asset.duration,
          thumb_url: `https://image.mux.com/{asset.playback_ids[0].id}/thumbnail.{png|jpg}`,
          vid_asset_id: upload.asset_id,
          vid_playback_id: asset.playback_ids[0].id,
          vid_url: `https://stream.mux.com/{asset.playback_ids[0].id}.m3u8`, // playback url  : "https://stream.mux.com/{PLAYBACK_ID}.m3u8"
          vid_tier: "free",
          created_at: serverTimestamp()
        });
      });
    }
  }, [upload]);
```

**Comment by EhanDuan** [comment]
I still need to learn more about js.

**Comment by davekiss** [comment]
Hey @EhanDuan -- while your approach may technically work in a localhost environment, you wouldn't want to make the API requests in this fashion from a production app for a few reasons:

1.) You'll hit some CORS issues in your browser for making XHR requests to a third-party domain.
2.) You won't want to expose your Mux auth credentials in the client side, as those are only meant for use within a secure context.

I'd recommend considering moving any code that's interacting with the Mux APIs to a server-side context where only you have visibility into the API flow.

Let me know if you have any follow-up questions on this!

**Comment by EhanDuan** [comment]
Thanks@davekiss -- I really appreciate your answer! I am still a new learner on `Mux` and `Nextjs`. So my following question may sound naive:

When you mentioned about the better solution, I am not sure how to realize it exactly. 
> moving any code that's interacting with the Mux APIs to a server-side context

Does it mean I need to put code into folder like below`src/pages/api/` ?
<img width="323" alt="image" src="https://user-images.githubusercontent.com/75397936/171293736-51973bc5-7ae9-4d77-9cf7-700b22554c4a.png">

**Comment by davekiss** [comment]
@EhanDuan yeah, for a Next.js app, that'd be a totally acceptable and workable solution 👍

**Comment by EhanDuan** [comment]
@davekiss Thanks a lot.
