### ISSUE TITLE
Mux with dotenv Error

### ISSUE THREAD

**Issue by EhanDuan** [muxinc/mux-node-sdk#167]
Hi, I have a question about `dotenv` process on `Mux`.

I initialized a `Video` from `new Mux`. Previously, I hard coded 2 params with plain string. It worked successfully.
```ts
const { Video } = new Mux(
"my_token_id",
  "my_token_secret"
);
```

However, when I installed `dotenv`, added `token_id` and `token_secret` into `.env` file, and changed the code like following
```ts
// TODO : Not hard coded
const { Video } = new Mux(
  process.env.MUX_TOKEN_ID,
  process.env.MUX_TOKEN_SECRET
);
``` 

It popped up an error like below. 
<img width="869" alt="image" src="https://user-images.githubusercontent.com/75397936/171488011-858d6115-f905-40f4-9143-737268eaf040.png">

I printed the variables which turned out to be undefined.

However, in the same project, `dotenv` worked for other dependency like `firestore`.
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/75397936/171487272-553e340d-b4a2-4b8c-9403-6b301ad22aed.png">

How do I handle this error? Thanks a lot.

**Comment by EhanDuan** [comment]
I just fixed it is my error that did not add the `NEXT_PUBLIC` prefix on these two variables.  I still need to learn much more on Nextjs!

**Comment by aminamos** [comment]
@EhanDuan I recommend against using `NEXT_PUBLIC` for secret environment variables, this option exposes environment variables to the browser.

You should be able to use `const { Video } = new Mux()` with the environment variables set privately without `NEXT_PUBLIC`. We have an example on this here: https://github.com/vercel/next.js/tree/canary/examples/with-mux-video

Thank you!
