### ISSUE TITLE
recent_asset_id is undefined in Video.LiveStreams.get(id) for first ~20 seconds of stream start (but not in HTTP API)

### ISSUE THREAD

**Issue by jbacco** [muxinc/mux-node-sdk#180]
To reproduce:
1. Start a live stream.
2. Wait about 5-10 seconds and then simultaneously perform the next two steps:
3. cURL: https://api.mux.com/video/v1/live-streams/<liveStreamId>-X GET -H "Content-Type: application/json" -u [credentials]
4. Node: Video.LiveStreams.get(id)
5. The cURL response should have a defined value for "active_asset_id", while the Node response will not.  This will remain the case for another 10-30 seconds of streaming.

Perhaps a caching issue?  I'm trying to use "active_asset_id" to identify new assets during a stream, but for now I'll rely on "recent_asset_ids" or the List Assets API if necessary.  It just seems erroneous to me that these calls would be returning different responses in that manner.

**Comment by dylanjha** [comment]
Hi @jbacco 

Hmmm, this is really odd. There is no code in SDK itself to do any caching, so a request from the SDK should get the same results as `curl`.

I will see if I can replicate it

**Comment by dylanjha** [comment]
Thanks @jbacco for opening this issue.

I'm trying to reproduce here -- in this video I'm getting the same responses from the node SDK `Video.LiveStreams.get(:id)` and with `curl "https://api.mux.com/video/v1/live-streams/:id`

Can you let me know if anything I'm doing here is different?

https://user-images.githubusercontent.com/764988/179665508-d8c19195-6b3d-45dc-98d8-4412292abe89.mov

If this is still happening I'd definitely want to dig in deeper.

**Comment by jbacco** [comment]
@dylanjha I've since rewritten my stream logic from scratch and can no longer replicate this issue, so I have to assume it was strictly on my end.  Thank you for looking into this and my apologies for giving you the runaround here.

**Comment by dylanjha** [comment]
No problem! Thanks for following up @jbacco -- if you see anything odd like that again please let us know. Either pinging here or via Mux Support
