### ISSUE TITLE
No `reconnect_slate_url` parameter available for creating and updating live streams

### ISSUE THREAD

**Issue by LauraBeatris** [muxinc/mux-node-sdk#184]
### Summary

The `create` and `update` method interfaces from `LiveStream` don't include the  `reconnect_slate_url` param mentioned in the Mux API docs

<img width="835" alt="Screenshot 2022-07-27 at 11 13 41" src="https://user-images.githubusercontent.com/48022589/181210123-2ab5b99b-aaca-42f1-ba14-e334402ef24b.png">

https://github.com/muxinc/mux-node-sdk/blob/d68c9cd29859c10d5a8d38c190feb92920c329b1/src/video/domain.ts#L269-L281

https://github.com/muxinc/mux-node-sdk/blob/d68c9cd29859c10d5a8d38c190feb92920c329b1/src/video/domain.ts#L283-L288

#### TS Compiler Error

<img width="816" alt="Screenshot 2022-07-27 at 11 15 10" src="https://user-images.githubusercontent.com/48022589/181210443-d7da5efa-51c0-4916-ab37-6d3f01a484e3.png">

At moment we're using `@ts-ignore` in order to be able to build the application, but would be nice to have this fixed in upcoming releases

**Comment by jaredsmith** [comment]
Thank you for your report. The "slates" feature for live streams just went into public beta a couple of days ago, and we're still getting the Node SDK updated to support the new API calls. I'm going to have it updated in the next few days.

**Comment by LauraBeatris** [comment]
@jaredsmith Makes sense! Thanks for the update :)

**Comment by jaredsmith** [comment]
Can you please try the v6.2.0 version that was recently published, @LauraBeatris?

**Comment by jaredsmith** [comment]
Closing due to lack of feedback.
