### ISSUE TITLE
Missing types export in package.json

### ISSUE THREAD

**Issue by mmvsk** [muxinc/mux-node-sdk#254]
There is no `types` field in `package.json` `exports`.

Because of this, TypeScript throws an error when used with the new `"moduleResolution": "bundler"`.

> error TS7016: Could not find a declaration file for module '@mux/mux-node'. 'node_modules/@mux/mux-node/dist/mux.mjs' implicitly has an 'any' type.

>  There are types at 'node_modules/@mux/mux-node/dist/mux.d.ts', but this result could not be resolved when respecting package.json "exports". The '@mux/mux-node' library may need to update its package.json or typings.

**Comment by cabello** [comment]
Please let us know when you do a new release, we just manually edited the package.json in node_modules and that fixed a bunch of errors.
