### ISSUE TITLE
Video.assets vs. Video.Assets

### ISSUE THREAD

**Issue by everettglovier** [muxinc/mux-node-sdk#28]
My code was working great and then one day i got a ton of errors. Was Video.assets changed to Video.Assets?

**Comment by JacquiManzi** [comment]
@everettglovier no changes have been made and it should have always been `Video.Assets`. I _do_ see an inconsistent comment that references `Video.assets`, but nothing around the structure of the Video object has changed. Could you share the error and the current version of this library you're using?

**Comment by JacquiManzi** [comment]
@everettglovier we did change this in the V2 release: https://github.com/muxinc/mux-node-sdk/blob/master/CHANGELOG.md

I did find an inconsistent comment in our code that still references `Video.assets` instead of `Video.Assets` and I will correct that.
