### ISSUE TITLE
Add support for node 8 (current LTS version)

### ISSUE THREAD

**Issue by dylanjha** [muxinc/mux-node-sdk#3]
On node 8.11.3 (current LTS) when running

> yarn add @mux/mux-node
> error @mux/mux-node@1.0.0-beta.2: The engine "node" is incompatible with this module. Expected version ">=10".

Since node recommends the LTS version for most users, it seems like this package should support it.

https://nodejs.org/en/

**Comment by JacquiManzi** [comment]
Thanks @dylanjha for catching that! Merged in https://github.com/muxinc/mux-node-sdk/pull/4 and will be included in the next release.
