### ISSUE TITLE
Webhook Types

### ISSUE THREAD

**Issue by shellscape** [muxinc/mux-node-sdk#303]
I was really hopeful that Mux was going to have a robust JS package with types, given how well-refined the overall product is. Sadly disappointed that types are so sparse, while the footprint of the Mux API and Webhook payloads are so wide. For instance: https://docs.mux.com/webhook-reference#video.asset.ready - the payload there is massive. Leaving it up to the consumer to properly type based on JSON documentation is not the best DX. Would love to see Mux improve and put additional effort into DX.

**Comment by dylanjha** [comment]
Thanks @shellscape , we're actually in the process of re-vamping a newly created Node SDK that has a number of enhancements. Let me check if the webhook types is in scope for that.

This is definitely an understandable pain point that we would like to improve!

**Comment by foureight84** [comment]
> 
Do you have a tentative release date for this revamped SDK? I'm hoping it would also address import issues as well in Typescript.

**Comment by TikiCat7** [comment]
also wondering if there is any update regarding webhook types :)

**Comment by dylanjha** [comment]
This as been done in version 8, the webhook types, import issues and better Types all around:

- https://github.com/muxinc/mux-node-sdk?tab=readme-ov-file#parsing-webhook-payloads
- https://github.com/muxinc/mux-node-sdk/releases/tag/v8.0.0
