### ISSUE TITLE
TypeError: mux_node_1.default is not a constructor

### ISSUE THREAD

**Issue by foureight84** [muxinc/mux-node-sdk#308]
SDK version: 7.3.1
Node version: 18.16.1

`import Mux from '@mux/mux-node';`

Produces:
TypeError: mux_node_1.default is not a constructor

Only require seems to work: `const Mux = require('@mux/mux-node');`

EDIT: This should make a difference but I am currently integrating Mux with NestJS and trying to create a dynamic module

**Comment by dylanjha** [comment]
Thanks @foureight84 -- we'll have a look at this. Seems like some app environments don't handle the `import` syntax, but others do.

We're working on a new version of this SDK and changing how it's built. We'll make sure we'll handle this case

**Comment by yldrmzffr** [comment]
We are still experiencing this problem. How can we solve it?

Node Version: 16
TS Version: 4.9.5
Mux SDK: 7.3.5

**Comment by dylanjha** [comment]
Hi @yldrmzffr do you mind giving a quick try with the v8 beta:

#327 

We've changed a number of things and it would help to check if this issue is resolved in the latest beta

**Comment by dylanjha** [comment]
This should be fixed in Version 8 -- please try migrating and report back if you still have an issue: https://github.com/muxinc/mux-node-sdk/releases/tag/v8.0.0
