### ISSUE TITLE
Add playback restriction example to JWT documentation

### ISSUE THREAD

**Issue by apettenati** [muxinc/mux-node-sdk#310]
Currently, there is no documentation or example showing how to pass params including the `playback_restriction_id` to the JWT options in the node documentation. It would be helpful if this was added. Thanks!

**Comment by dylanjha** [comment]
Hi @apettenati, thanks for bringing this up! I hope you figured it out, and we can definitely add more documentation.

As of right now we have [one example here](https://docs.mux.com/guides/video/secure-video-playback#5-sign-the-json-web-token-jwt) with the node SDK if you click the "node" tab

Short answer is you pass in `playback_restriction_id:` in with the extra `params`

```node
const { JWT } = require('@mux/mux-node');

JWT.sign(playbackId, {
  params: { playback_restriction_id: YOUR_PLAYBACK_RESTRICTION_ID },
})
```

let me know if that helps!

**Comment by apettenati** [comment]
Yes, thank you! I have this working, I just thought I'd recommend adding an example as well.

**Comment by rubenheymans** [comment]
how do you create the playback restriction?
when do you create the signed playback id?
how do you insert it to you mux-player?
how do you know the signed playback id is expired and you need to create a new one?
this is so confusing

**Comment by rubenheymans** [comment]
ok so I can create the playback restriction using postman (is there a ui option coming?)

I create the signed playback id everytime I load the video asset but this makes loading the asset slower

Insert it into mux-player like this:
 [attr.playback-id]="file.playbackId"
[attr.playback-token]="signedUrls.playback"
[attr.thumbnail-token]="signedUrls.thumbnail"
[attr.storyboard-token]="signedUrls.storyboard"

How do you know the signed playback id is expired and you need to create a new one?
Can't find any info about this?

**Comment by dylanjha** [comment]
@rubenheymans you'll want to set the expiration to a timeframe longer than the length of the video, with some buffer because a user might pause and come back later, scrub, etc.

If the token is expired the player will throw a 403 error and you can catch that, make an API request to get refreshed tokens.

**Comment by dylanjha** [comment]
We recently refreshed the guide for doing signed playback URLs (w/ optional playback restrictions): https://docs.mux.com/guides/secure-video-playback

Closing because this is not a specific issue related to the node SDK
