### ISSUE TITLE
Error: secretOrPrivateKey must be an asymmetric key when using RS256

### ISSUE THREAD

**Issue by roninaruka** [muxinc/mux-node-sdk#311]
`const token = Mux.JWT.signPlaybackId('some-playback-id');`

when create token gettign error
```
Error: secretOrPrivateKey must be an asymmetric key when using RS256
    at Object.module.exports [as sign] (/home/chhayya/Documents/fitscopeV2/fitscopeV2_Backend/node_modules/.pnpm/jsonwebtoken@9.0.0/node_modules/jsonwebtoken/sign.js:124:22)
    at Function.signPlaybackId (/home/chhayya/Documents/fitscopeV2/fitscopeV2_Backend/node_modules/.pnpm/@mux+mux-node@7.3.1/node_modules/@mux/mux-node/src/utils/jwt.ts:155:16)
    at Function.sign (/home/chhayya/Documents/fitscopeV2/fitscopeV2_Backend/node_modules/.pnpm/@mux+mux-node@7.3.1/node_modules/@mux/mux-node/src/utils/jwt.ts:109:17)
    at /home/chhayya/Documents/fitscopeV2/fitscopeV2_Backend/src/routes/content/categories.ts:170:47
    at Array.map (<anonymous>)
    at /home/chhayya/Documents/fitscopeV2/fitscopeV2_Backend/src/routes/content/categories.ts:168:60
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/chhayya/Documents/fitscopeV2/fitscopeV2_Backend/src/routes/content/categories.ts:167:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[ERROR] 13:10:37 Error: secretOrPrivateKey must be an asymmetric key when using RS256
```

**Comment by dylanjha** [comment]
@roninaruka do you have environment variables set:

`process.env.MUX_SIGNING_KEY`
`process.env. MUX_PRIVATE_KEY`

**Comment by roninaruka** [comment]
Thanks @dylanjha i have set

**Comment by dylanjha** [comment]
Okay this is probably an issue with the keySecret.

Which way did you get your key:

- Created in the Mux Dashboard & copied to clipboard in the UI
- Created [via the API](https://docs.mux.com/api-reference#system/operation/create-signing-key)
- Created in the Mux Dashboard & downloaded as `.pem` file

Can you try one of the first 2 options? Probably easiest if you just create in the dashboard and click "copy" to get the Base-64 encoded private key.

You can get to this screen from Settings > Signing Keys in the left nav and then click "Generate new key"

<img width="760" alt="signing-key_2023-08-24_15-11-35" src="https://github.com/muxinc/mux-node-sdk/assets/764988/8d30be77-043d-49db-8461-4be8e3780259">

**Comment by roninaruka** [comment]
@dylanjha Thanks its working fine but one more question  i have pass expiration in option like `{ expiration: ((new Date()).getTime() + 50).toString() }` for 50 sec 
but its not wokring
is anything  wrong here ??

**Comment by dylanjha** [comment]
@roninaruka well, 50 seconds is probably too short (the expiration has to be _at least_ longer than the duration of the video

I'm noticing that this should be documented better, but the `expiration` value gets passed into `jwt.sign` as the `expiresIn` value in [this `jsonwebtoken` dependency](https://www.npmjs.com/package/jsonwebtoken)

Values are like this:

- `50` (50 seconds)
- `50s` (50 seconds)
- `7d` (7 days) -- the default
- `4h`  (4 hours)

See here for [the syntax](https://github.com/vercel/ms)
