### ISSUE TITLE
Add `generated_subtitles` to the interface CreateAssetParams.input

### ISSUE THREAD

**Issue by nwaughachukwuma** [muxinc/mux-node-sdk#318]
Auto-generated captions are now supported in on-demand videos on Mux, and require specifying `generated_subtitles` field when creating a new asset using `Video.Assets.create`. It would be nice, even necessary, to add an interface for this field on the SDK. 

```
// POST https://api.mux.com/v1/assets
{
    "input": [
        {
            "url": "...",
            "generated_subtitles": [
                {
                    "language_code": "en",
                    "name": "English CC"
                }
            ]
        }
    ],
    "playback_policy": "public"
}
```

I'm happy to send a PR if there's nothing in the works.

### References

- https://www.mux.com/blog/auto-generated-captions-for-on-demand-video-have-arrived-crowd-roars-with-applause
- https://docs.mux.com/guides/video/add-autogenerated-captions-and-use-transcripts?_gl=1*kilj6x*_ga*MjA3MTM2NDc4Ny4xNjk4MDk0ODQx*_ga_D3BFYPQXX7*MTY5ODg3MDUzOC4zLjEuMTY5ODg3MDU0NS4wLjAuMA..

**Comment by philcluff** [comment]
Hi @nwaughachukwuma, we're actively working on these missing fields and APIs in the node SDKs, we'll let you know when there's a release.

**Comment by nwaughachukwuma** [comment]
Alright, thanks! And please feel free to ask.

> I'm happy to send a PR if there's nothing in the works.

**Comment by nwaughachukwuma** [comment]
I see the option is now part of the new release. I'm closing the issue.
