### ISSUE TITLE
Issue with new "react-native-nodemediaclient" version

### ISSUE THREAD

**Issue by safee-cases** [muxinc/mux-node-sdk#334]
Hey everybody ! 

I used this old version of this guide to handle livestream video on my app:
[https://www.mux.com/blog/live-streaming-with-react-native]

Unfortunately the 'react-native-nodemediaclient' version used is deprecated. I updated it to the last version and replace with new syntax:

Before update I used NodeCameraView
```
  <NodeCameraView
    style={styles.cameraBack}
    ref={cameraViewRef}
    outputUrl={url + streamKey}
    camera={config.cameraConfig}
    audio={config.audioConfig}
    video={config.videoConfig}
     autopreview
     audioEnable={store.isMuted}
  />
```

After update I'm now using NodePublisher

```
<NodePublisher
     ref={cameraViewRef}
     style={styles.cameraBack}
     url={url + streamKey}
     camera={config.cameraConfig}
     audioParams={config.audioConfig}
      videoParams={config.videoConfig}
       autopreview
      audioEnable={store.isMuted}
/>
```

With 'NodePublisher' I fixed the issue where my livestream didn't work anymore but I got now an issue with Mux because my stream don't upload to mux anymore so I can't replay it on my app 

Is anyone is on the same situation than me and found some solutions ? 😄

**Comment by JacquiManzi** [comment]
Hi @safee-cases ! Without additional information, this doesn't appear to be an issue with the SDK. However, if you reach out to https://mux.com/support with more information regarding the specific issues you are experiencing around stream uploads we might be able to help out. Thanks!
