### ISSUE TITLE
Confusion regarding missing fields in AbridgedVideoView interface after upgrading to SDK v8.0.0

### ISSUE THREAD

**Issue by RaulEspinozaC** [muxinc/mux-node-sdk#336]
Hello Mux team,

I'm encountering an issue after upgrading our application to use the latest version (v8.0.0) of the Mux SDK. Previously, we were relying on the `VideoViewsListResponse` interface provided by the SDK to capture and store video view details in our database. However, after the upgrade, we noticed that two important fields, namely `watch_time` and `viewer_experience_score`, are missing from the interface definition.

Upon investigating further, I found that the API documentation for "/data/v1/video-views" still mentions these fields as part of the response payload. This has caused confusion for me as to whether the SDK or the API documentation is correct.

Could you please provide clarification on the following:

1. Are the` watch_time` and `viewer_experience_score` fields still supported in the latest version of the SDK (v8.0.0)?
2. If these fields have been deprecated or removed, what is the recommended approach for retrieving similar metrics?
3. Is there any discrepancy between the SDK documentation and the actual behavior/API response?

It's crucial for our application to accurately capture and store video view details, so any guidance or clarification on this matter would be greatly appreciated.

**Comment by philcluff** [comment]
Hey @RaulEspinozaC, thanks for raising this, this is an oversight in the V8 SDK, these fields should be here, we're working on a patch now.

**Comment by RaulEspinozaC** [comment]
Thanks @philcluff for your response, I'm a member of the Vidzing team and I'm eager to assist in any way. Please don't hesitate to reach out if there's anything I can do to contribute to the patch development or testing efforts.

Looking forward to the updated version and continuing to work closely with the Mux team to ensure the seamless integration of our application.

**Comment by philcluff** [comment]
Hey @RaulEspinozaC, this should be addressed in https://github.com/muxinc/mux-node-sdk/releases/tag/v8.1.1 - can you give it a try and see if it resolves your problem?

Apologies again for missing this. 

Thanks!

**Comment by RaulEspinozaC** [comment]
Hey @philcluff, it did fixed my problem.

Thank you!
