### ISSUE TITLE
Bug: Setting "test: true" when creating a direct upload does not create a test asset

### ISSUE THREAD

**Issue by calvin-william-smith** [muxinc/mux-node-sdk#402]
As the title says, the asset created is not limited to 10 seconds and watermarked as indicated in the docs and therefore I assume counts towards billing.

Using video.uploads.create:

```
      new_asset_settings: { 
        playback_policy: ['public'],
        encoding_tier: 'baseline',
        test: true // limits playback to 10 seconds and watermarks video but incurs no cost
      },
```

**Comment by philcluff** [comment]
Hey @calvin-william-smith, sorry about this, the documentation is a little misleading here - for a direct upload to create a test asset, you need to set `test: true` at the top level of the direct upload object, not in `new_asset_settings`. I'll make sure we track updating the documentation to make this more clear.

Thanks!
