### ISSUE TITLE
Type of CreateAssetParams.input should not be required

### ISSUE THREAD

**Issue by ebeloded** [muxinc/mux-node-sdk#52]
[CreateAssetParams](https://github.com/muxinc/mux-node-sdk/blob/master/types/interfaces/CreateAssetParams.ts) interface requires 'input' to be defined.

This would break the [example](https://docs.mux.com/docs/direct-upload#creating-an-upload-route-in-the-application) of direct upload in Mux Docs.
```ts
 const upload = await Video.Uploads.create({
    // Set the CORS origin to your application.
    cors_origin: 'https://your-app.com',

    // Specify the settings used to create the new Asset after
    // the upload is complete
    new_asset_settings: { // <- this is CreateAssetParams without input
      passthrough: id,
      playback_policy: 'public',
    }
  });

```

**Comment by dylanjha** [comment]
Good catch @ebeloded! Ty!
