### ISSUE TITLE
Errors thrown are not instance of `Error` class

### ISSUE THREAD

**Issue by iamvajid** [muxinc/mux-node-sdk#54]
Though it may not be a major issue in integrating with mux, it would be nice if the errors thrown out from sdk are instances of native `Error` class. It means a lot to the developer experience

**Comment by mmcc** [comment]
Hi there, can you give an example of when you're not seeing an instance of `Error` thrown?

**Comment by aminamos** [comment]
Hi @iamvajid - if you're still experiencing this issue, let us know and we will re-open this issue.
