### ISSUE TITLE
Video.assets.list() does not support page and limit options

### ISSUE THREAD

**Issue by AndrewBarba** [muxinc/mux-node-sdk#6]
`Video.assets.list()` should accept `limit: number` and `page: number` options as documented here: https://docs.mux.com/v1/reference#list-assets

**Comment by JacquiManzi** [comment]
Thanks for catching that- I'll add that functionality now.

**Comment by JacquiManzi** [comment]
@AndrewBarba this has been fixed in the latest release (1.0.0). Let me know if there is anything else that you run into- it is extremely appreciated!

**Comment by AndrewBarba** [comment]
You got it, thanks for updating so quickly
