### ISSUE TITLE
Firebase Deploy Error: "Mux is not a constructor"

### ISSUE THREAD

**Issue by CubitSpeed** [muxinc/mux-node-sdk#61]
I'm having an issue when trying to deploy code with the newest Mux version (3.0.2 -- using typescript types). Note: previous Mux versions (before Typescript support worked fine)

I'm deploying my code to [Firebase](https://firebase.google.com/)'s cloud functions via the `firebase deploy --only functions` command.

The code is able to build correctly without errors, but Firebase's deploy command will throw the following:
```
Error: Error occurred while parsing your function triggers.

TypeError: Mux is not a constructor
    at Object.<anonymous> (/mnt/l/projects/my_fb_project/backend/functions/lib/index.js:44:57)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /mnt/l/projects/my_fb_project/backend/functions/node_modules/firebase-tools/lib/triggerParser.js:15:15
    at Object.<anonymous> (/mnt/l/projects/my_fb_project/backend/functions/node_modules/firebase-tools/lib/triggerParser.js:53:3)
```

**Comment by dylanjha** [comment]
@CubitSpeed interesting, thanks for opening this.

I'm not aware of how typescript would have affected firebase deploys. If you can provide some example code and reproduction steps I'm happy to take a look.

**Comment by kevmo314** [comment]
I'm also running into this issue. Just instantiating `Mux` with any firebase function project will crash.

**Comment by kevmo314** [comment]
I temporarily worked around this by using

```
const Mux = require('@mux/mux-node');
```

instead of the standard ts `import Mux from '@mux/mux-node'`. Inspecting the typescript output, it produces:

```
var mux_node_1 = require('@mux/mux-node');

var Mux = mux_node_1.default(...);
```

and unsurprisingly, `mux_node_1.default` is undefined. Manually confirming this, `require('@mux/mux-node').default` is undefined.

I'm guessing this project has its exports misconfigured, specifically default exports should be `module.exports.default = `. I sent a pull request to add an ES6 default export.

**Comment by dylanjha** [comment]
@kevmo314 @CubitSpeed this is fixed now in `v3.0.4`. Thank you!

**Comment by CubitSpeed** [comment]
Thank you everyone. Looks like it is working now

**Comment by nicoladj77** [comment]
I am getting this same issue in a firebase function

```
const Mux = require("@mux/mux-node");

module.exports = async (data, context) => {
  console.log('start');
  const { Video } = new Mux(xxx, yyy);

  try {
    const upload = await Video.Uploads.create({
      new_asset_settings: {
        playback_policy: 'public'
      }
    });
    console.log(upload);
    return upload.url;
  } catch (e) {
    return ''
  }

}
```

and the error 

TypeError: Mux is not a constructor
    at module.exports (/workspace/src/getSignedUrl/index.js:5:21)
    at fixedLen (/layers/google.nodejs.yarn/yarn_modules/node_modules/firebase-functions/lib/providers/https.js:72:41)
    at /layers/google.nodejs.yarn/yarn_modules/node_modules/firebase-functions/lib/common/providers/https.js:407:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by nicoladj77** [comment]
This is happening on the 5.0.0 RC and downgrading to 3.3.6 fixes the issue @dylanjha so it might be a regression. yarn add automatically installs the release candidate which is not ideal

**Comment by nicoladj77** [comment]
@ljs19923 I downgraded the package in package.json to 3.3.2

    "@mux/mux-node": "3.3.2",
