### ISSUE TITLE
Video.assests.deleteAsset() is an inconsistent name

### ISSUE THREAD

**Issue by AndrewBarba** [muxinc/mux-node-sdk#7]
`Video.assests.deleteAsset()` feels like an inconsistent name compared to `get()` and `list()`. I think this should be renamed to `remove()`

**Comment by JacquiManzi** [comment]
That's a really good point, I'll change this from `deleteAsset` to `remove`. Thanks for the input!

**Comment by AndrewBarba** [comment]
Or just `delete`! Naming... so difficult. Thanks though appreciate it!

**Comment by JacquiManzi** [comment]
Changed to `remove` in the latest release (1.0.0). I avoided `delete` because it's a reserved word, naming _is_ so hard haha. Thanks again!

**Comment by AndrewBarba** [comment]
Perfect
