### ISSUE TITLE
can't resolve `fs` in node_modules/@mux/mux-node/src/utils

### ISSUE THREAD

**Issue by 1stevengrant** [muxinc/mux-node-sdk#74]
Hi folks,
I'm trying to extend our CMS to integrate with Mux by creating a custom field that will allow an author to create a video asset.

I'm creating a custom JavaScript component in VueJS and I'm looking to take the public URL from the author and then client-side, generate the new video asset.

I have a JS method 

```
        generateNewAsset() {
            console.log('kick off the new asset generation')
            const muxClient = new Mux(process.env.MIX_MUX_ACCESS_TOKEN, process.env.MIX_MUX_SECRET_KEY)
            console.log(muxClient)
        }
```

but running into 

```
ERROR in ./node_modules/@mux/mux-node/src/utils/jwt.js
Module not found: Error: Can't resolve 'fs' in '/Users/stevengrant/Sites/ghijk/node_modules/@mux/mux-node/src/utils'
 @ ./node_modules/@mux/mux-node/src/utils/jwt.js 6:11-24
 @ ./node_modules/@mux/mux-node/src/mux.js

```

is this because the Node SDK is for server-side JS rather than client-side?

Any advice appreciated.

**Comment by GeneticGenesis** [comment]
Hey @1stevengrant, 

You're correct, the Mux Node SDK must not be used in client side code - doing so would create security vulnerabilities in your application. 

Generally, CMS integrations with Mux run on the server side of the application, creating Direct Upload URLs which are passed back to the front end, which allow your users to securely, directly upload files. You can use our Upchunk library to make this a little easier: 

https://docs.mux.com/docs/direct-upload
https://github.com/muxinc/upchunk

Let me know if you have any more questions, if you want to ask something outside Github, feel free to drop us an email on help@mux.com.

Thanks!

**Comment by 1stevengrant** [comment]
Thanks. I think I have something that will work :)
