### ISSUE TITLE
Expose JWT and Webhooks objects on instance

### ISSUE THREAD

**Issue by jacob-israel-turner** [muxinc/mux-node-sdk#75]
Hello!  First of all, thanks for building the Node SDK!  It's been very valuable for our team.

Would the team be ok with attaching the JWT and Webhooks objects to the mux instance?  Currently, they're [only available on the top-level class](https://github.com/muxinc/mux-node-sdk/blob/master/src/mux.js#L68).  It's fine, but was a little confusing when I was initially looking for the JWT object, as everything else we use has been on the instance itself.  Seems like it would be a simple change - simply attach them within the constructor at initialization time, [like we already do with Video and Data](https://github.com/muxinc/mux-node-sdk/blob/master/src/mux.js#L58).

If the team would be ok with this, I'd be happy to put together a PR with the changes!

**Comment by dylanjha** [comment]
@jacob-israel-turner I'd be happy to review a PR with these changes it came up a few other times:

* #68 
* #44 

Feel free to have a stab at it!

**Comment by dylanjha** [comment]
This is done in Version 8:

https://github.com/muxinc/mux-node-sdk/releases/tag/v8.0.0
