### ISSUE TITLE
Property SigningKeys does not exist on type Video

### ISSUE THREAD

**Issue by cwqt** [muxinc/mux-node-sdk#79]
Looks like a small typing problem, in `/node_modules/@mux/mux-node/types/mux.d.ts` shows that the `SigningKey` isn't part of the typing for `Video`

```typescript
export declare class Video extends Base {
  Assets: Assets;
  LiveStreams: LiveStreams;
  Uploads: Uploads;
  Metrics: Metrics;
}
```

But in `/node_modules/@mux/mux-node/src/video/video.js` `SigningKeys` is in the class defintion.

**Comment by dylanjha** [comment]
Thanks for catching this @cwqt ! We'll work on a fix!
