### ISSUE TITLE
[Bug] per_title_encode should be in CreateAssetParams type definitions

### ISSUE THREAD

**Issue by LucienLee** [muxinc/mux-node-sdk#80]
According to your [per-title encoding guide](https://docs.mux.com/docs/per-title-encoding#1-enabling-instant-per-title-encoding), `per_title_encode` should be in the CreateAssetParams [definitions](https://github.com/muxinc/mux-node-sdk/blob/master/types/interfaces/CreateAssetParams.ts)

**Comment by GeneticGenesis** [comment]
Thanks for the report @LucienLee, we'll get this fixed. 

Thanks!
