### ISSUE TITLE
[Bug] Type is wrong for Asset type

### ISSUE THREAD

**Issue by alexarena** [muxinc/mux-node-sdk#86]
On the `Asset` interface, the  `max_stored_resolution?` is defined as `'Audio-only' | 'SD' | 'HD' | 'FHD' | 'UHD'`.  In practice, the Mux API returns `Audio only` (no `-`).

I think the fix for this would just be to change the definition in `Asset.ts` to reflect what's being returned from your API in practice, but I wanted to open as an issue first to confirm that this is in fact a bug.

**Comment by GeneticGenesis** [comment]
Get @alexarena, thanks for raising this, indeed it looks like this is incorrect, the API returns `Audio only` as you described. 

I'll propagate this change through our SDKs and documentation.

Thanks!

**Comment by GeneticGenesis** [comment]
This is addressed in #87
